server:
  port: 8080
spring:
  application:
    name: StellarTown-server
  datasource:
    dynamic:
      primary: db_stellar_town_user
      strict: false
      datasource:
        db_stellar_town_user:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/db_stellar_town_user?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
          username: root
          password: root
          hikari:
            minimum-idle: 5
            maximum-pool-size: 10
        db_stellar_town_post:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/db_stellar_town_post?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&collation=utf8_bin
            username: root
            password: root
            hikari:
              minimum-idle: 5
              maximum-pool-size: 10
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
## springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: org.pp.boot3
#  # knife4j的增强配置
#  enable: true
#  setting:
#    language: zh_cn

# 常量定义
application:
  security:
    jwt:
      secret-key: hllwzstellartownhllwzstellartownhllwzstellartown
      # 定义有效时间：三天
      expiration: 259200000
      # 定义刷新token的有效时间：七天
      refresh-token:
          expiration: 604800000 # 7 days
minio:
  endpoint: http://127.0.0.1:9999
  accessKey: adminminio
  secretKey: adminminio
  bucketName: stellar-town
